version: '3.8'

services:
  touba-khelcom:
    build: .
    ports:
      - "5000:5000"
    container_name: touba-khelcom-app
    restart: unless-stopped
    volumes:
      # Optionnel: pour le développement, vous pouvez monter le code source
      # - .:/usr/share/nginx/html:ro
