# Version ultra-simple pour débogage
FROM nginx:alpine

# Copier seulement les fichiers essentiels
COPY index.html /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/
COPY img/ /usr/share/nginx/html/img/

# Exposer le port 80
EXPOSE 80
